//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlhx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public long admin_id { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
        public int admin_power { get; set; }
        public bool admin_isDel { get; set; }
    }
}
