//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlhx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choos
    {
        public long choose_id { get; set; }
        public long choose_ownStudentId { get; set; }
        public long choose_ownExperimentId { get; set; }
        public bool choose_isDel { get; set; }
        public string choose_ExperimenTimet { get; set; }
    
        public virtual Experiment Experiment { get; set; }
        public virtual Student Student { get; set; }
    }
}
