//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlhx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dynamic
    {
        public long dynamic_id { get; set; }
        public string dynamic_title { get; set; }
        public string dynamic_body { get; set; }
        public System.DateTime dynamic_publicTime { get; set; }
        public int dynamic_class { get; set; }
        public Nullable<bool> dynamic_isIndex { get; set; }
        public bool dynamic_isDel { get; set; }
        public Nullable<int> dynamic_softwareCategory { get; set; }
    }
}
