//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlhx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Chooses = new HashSet<Choos>();
        }
    
        public long student_id { get; set; }
        public string student_number { get; set; }
        public string student_name { get; set; }
        public string student_professional { get; set; }
        public string student_class { get; set; }
        public int student_grade { get; set; }
        public string student_password { get; set; }
        public Nullable<long> student_proDirectionId { get; set; }
        public bool student_isDel { get; set; }
    
        public virtual ICollection<Choos> Chooses { get; set; }
        public virtual Professional Professional { get; set; }
    }
}
