//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlhx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WlhxEntities : DbContext
    {
        public WlhxEntities()
            : base("name=WlhxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Choos> Chooses { get; set; }
        public DbSet<Dynamic> Dynamics { get; set; }
        public DbSet<Experiment> Experiments { get; set; }
        public DbSet<ExperimentTime> ExperimentTimes { get; set; }
        public DbSet<Professional> Professionals { get; set; }
        public DbSet<StudentImg> StudentImgs { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
